name: tquestion_tag_app
description: "A Flutter application for learning Tag Question."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  

  # Fonts & Animations
  google_fonts: ^6.1.0
  lottie: ^3.1.0

  # Storage & State Management
  shared_preferences: ^2.1.0
  provider: ^6.1.1

  # UI Animations Package
  animations: ^2.0.8
  url_launcher: ^6.3.2
  audioplayers: ^6.0.0
  http: ^1.6.0
  google_generative_ai: ^0.4.7
  flutter_gemini: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/sounds/
